"""
Generates sample_data/generated_entries/*.json — five example rolodex entries
showing the expected output of the ingestion pipeline for the five sample
LinkedIn profiles in sample_data/linkedin_profiles/.

These are static fixtures (not generated by a live OpenAI call) so the repo
is immediately inspectable without an API key. They match the exact shape
returned by GET /api/v1/contacts/{id} (ContactRead), with the 1536-dim
embedding vector replaced by a placeholder string for readability.
"""
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

OUT_DIR = Path(__file__).parent / "sample_data" / "generated_entries"
OUT_DIR.mkdir(parents=True, exist_ok=True)

NOW = datetime.now(timezone.utc).isoformat()
EMBEDDING_PLACEHOLDER = "<1536-dim float vector, omitted for readability — see /docs response for real shape>"

ENTRIES = [
    {
        "file": "01_priya_shenoy.json",
        "data": {
            "id": str(uuid.uuid4()),
            "full_name": "Priya Shenoy",
            "headline": "Senior Backend Engineer @ Finlynk | Ex-Razorpay | Distributed Payments Systems",
            "linkedin_url": "https://www.linkedin.com/in/priya-shenoy-example",
            "photo_url": None,
            "current_company": "Finlynk",
            "current_title": "Senior Backend Engineer",
            "location": "Bengaluru, Karnataka, India",
            "industry": "FinTech / Payments Infrastructure",
            "summary": "Backend engineer with 9 years building payments infrastructure. "
            "Leads the payments team at Finlynk, previously built the core payouts "
            "engine at Razorpay. Focused on correctness, ledger integrity, and "
            "distributed-systems reliability over cleverness.",
            "experience": [
                {
                    "title": "Senior Backend Engineer",
                    "company": "Finlynk",
                    "start_date": "2022-01",
                    "end_date": None,
                    "description": "Leads the payments infrastructure team (6 engineers). "
                    "Redesigned the ledger and reconciliation pipeline (Kafka + Postgres, "
                    "exactly-once semantics), cutting settlement mismatches by 94% and "
                    "audit close time from 5 days to 6 hours.",
                },
                {
                    "title": "Backend Engineer",
                    "company": "Razorpay",
                    "start_date": "2018-06",
                    "end_date": "2021-12",
                    "description": "Built and scaled the payouts engine handling ~2M "
                    "transactions/day. Migrated a monolith payout service to an "
                    "event-driven architecture on Kafka. Mentored 4 junior engineers.",
                },
                {
                    "title": "Software Engineer",
                    "company": "Freshworks",
                    "start_date": "2016-08",
                    "end_date": "2018-05",
                    "description": "Worked on billing systems for the CRM product.",
                },
            ],
            "education": [
                {
                    "school": "National Institute of Technology Karnataka (NITK), Surathkal",
                    "degree": "B.Tech",
                    "field_of_study": "Computer Science",
                    "start_year": "2012",
                    "end_year": "2016",
                }
            ],
            "skills": [
                "Distributed Systems",
                "Idempotent System Design",
                "System Design Mentoring",
                "Incident Response",
            ],
            "technologies": ["Kafka", "PostgreSQL", "Go", "Python", "AWS"],
            "domains": ["FinTech", "Payments"],
            "capabilities": [
                "Can architect exactly-once payment/ledger pipelines",
                "Can lead incident response for payments outages",
                "Can mentor engineers on distributed systems fundamentals",
            ],
            "interests": ["Payments infrastructure", "Idempotency", "Ledger correctness"],
            "relevance_summary": "Priya is the person to talk to when a payments or "
            "ledger system needs to be provably correct, not just fast. She's led two "
            "major reconciliation rewrites and is strong on Kafka-based exactly-once "
            "processing. Worth reaching out for backend architecture reviews on "
            "anything involving money movement, or for on-call/incident-response "
            "process design in a fintech context.",
            "relevance_tags": [
                "FinTech specialist",
                "Payments infrastructure",
                "Distributed systems",
                "Senior backend engineer",
                "Incident response lead",
            ],
            "connection_notes": [
                {
                    "note_type": "met_at_hackathon",
                    "text": "Met at the Bengaluru FinTech builders meetup, Feb 2026.",
                    "created_at": NOW,
                }
            ],
            "source_type": "text",
            "created_at": NOW,
            "updated_at": NOW,
            "embedding": EMBEDDING_PLACEHOLDER,
        },
    },
    {
        "file": "02_arjun_mehta.json",
        "data": {
            "id": str(uuid.uuid4()),
            "full_name": "Arjun Mehta",
            "headline": "Co-Founder & CEO at Verdantly (Seed) | Ex-McKinsey | Building the "
            "API layer for carbon accounting",
            "linkedin_url": "https://www.linkedin.com/in/arjun-mehta-example",
            "photo_url": None,
            "current_company": "Verdantly",
            "current_title": "Co-Founder & CEO",
            "location": "San Francisco Bay Area",
            "industry": "Climate Tech",
            "summary": "Founder of Verdantly, a seed-stage carbon-accounting API company "
            "for manufacturing supply chains. Five years advising Fortune 500 "
            "manufacturing and logistics clients at McKinsey before founding. Raised "
            "$4.2M seed and grew the team from 2 to 22.",
            "experience": [
                {
                    "title": "Co-Founder & CEO",
                    "company": "Verdantly",
                    "start_date": "2025-01",
                    "end_date": None,
                    "description": "Building carbon-accounting APIs for manufacturing "
                    "supply chains. Raised $4.2M seed (Lowercarbon Capital, angels). "
                    "Grew team from 2 to 22. Landed first 40 mid-market manufacturing "
                    "customers.",
                },
                {
                    "title": "Engagement Manager, Sustainability Practice",
                    "company": "McKinsey & Company",
                    "start_date": "2019-07",
                    "end_date": "2024-12",
                    "description": "Advised manufacturing and logistics clients across "
                    "APAC on decarbonization strategy and supply-chain emissions "
                    "reporting.",
                },
                {
                    "title": "Business Analyst",
                    "company": "McKinsey & Company",
                    "start_date": "2017-07",
                    "end_date": "2019-06",
                    "description": None,
                },
            ],
            "education": [
                {
                    "school": "Indian Institute of Management, Ahmedabad",
                    "degree": "MBA",
                    "field_of_study": None,
                    "start_year": "2015",
                    "end_year": "2017",
                },
                {
                    "school": "Birla Institute of Technology and Science, Pilani",
                    "degree": "B.E.",
                    "field_of_study": "Mechanical Engineering",
                    "start_year": "2011",
                    "end_year": "2015",
                },
            ],
            "skills": ["Fundraising", "Early-stage Hiring", "Supply Chain Strategy"],
            "technologies": [],
            "domains": ["Climate Tech", "Manufacturing", "Supply Chain"],
            "capabilities": [
                "Can advise on seed-stage fundraising and investor targeting",
                "Can advise on enterprise sales motion for climate-tech / manufacturing buyers",
                "Can advise on early-stage hiring (0 to 20 employees)",
            ],
            "interests": ["Climate tech", "Angel investing", "Decarbonization"],
            "relevance_summary": "Arjun is a strong contact for anyone building an "
            "enterprise or climate-tech startup selling into manufacturing: he's raised "
            "a seed round, scaled a team from 2 to 22, and spent five years inside "
            "McKinsey's manufacturing client base. He's also an active angel investor "
            "in climate tech, so worth reaching out both for fundraising advice and as "
            "a potential investor.",
            "relevance_tags": [
                "Early-stage startup founder",
                "Climate tech",
                "Fundraising",
                "Angel investor",
                "Enterprise sales into manufacturing",
            ],
            "connection_notes": [],
            "source_type": "text",
            "created_at": NOW,
            "updated_at": NOW,
            "embedding": EMBEDDING_PLACEHOLDER,
        },
    },
    {
        "file": "03_lena_park.json",
        "data": {
            "id": str(uuid.uuid4()),
            "full_name": "Lena Park",
            "headline": "Applied ML Scientist, Recommendation Systems @ Meta | PhD Stanford "
            "| Prev. Netflix",
            "linkedin_url": "https://www.linkedin.com/in/lena-park-example",
            "photo_url": None,
            "current_company": "Meta",
            "current_title": "Applied ML Scientist, Reels Ranking",
            "location": "Menlo Park, California",
            "industry": "Machine Learning / Recommendation Systems",
            "summary": "ML scientist specializing in recommendation and ranking systems, "
            "with a PhD from Stanford in off-policy evaluation. Leads ranking research "
            "for Reels at Meta; previously built the counterfactual evaluation "
            "framework for Netflix's homepage ranking.",
            "experience": [
                {
                    "title": "Applied ML Scientist, Reels Ranking",
                    "company": "Meta",
                    "start_date": "2023-03",
                    "end_date": None,
                    "description": "Leads ranking model research for Reels "
                    "recommendations. Shipped a multi-task ranking model that improved "
                    "watch-time by 3.1% in a production A/B test across the whole "
                    "surface.",
                },
                {
                    "title": "Senior Research Scientist",
                    "company": "Netflix",
                    "start_date": "2019-09",
                    "end_date": "2023-02",
                    "description": "Row-ranking and off-policy evaluation for the "
                    "Netflix homepage. Built the counterfactual evaluation framework "
                    "used to validate ranking changes before full rollout.",
                },
            ],
            "education": [
                {
                    "school": "Stanford University",
                    "degree": "PhD",
                    "field_of_study": "Computer Science (Machine Learning)",
                    "start_year": "2015",
                    "end_year": "2019",
                },
                {
                    "school": "Seoul National University",
                    "degree": "B.S.",
                    "field_of_study": "Computer Science",
                    "start_year": "2011",
                    "end_year": "2015",
                },
            ],
            "skills": ["Causal Inference", "Research Leadership", "A/B Testing"],
            "technologies": ["PyTorch"],
            "domains": ["Machine Learning", "Recommendation Systems"],
            "capabilities": [
                "Can design and validate off-policy / counterfactual evaluation "
                "frameworks for ranking systems",
                "Can lead applied research teams shipping ranking models to production",
                "Can review recommendation-systems research (RecSys/KDD/NeurIPS)",
            ],
            "interests": ["Recommendation systems research", "Mentoring PhD interns"],
            "relevance_summary": "Lena is a top contact for anything involving "
            "production recommendation or ranking systems, especially where rigorous "
            "offline evaluation matters before a risky rollout. She has shipped ranking "
            "changes at both Netflix and Meta scale and is an active RecSys/NeurIPS "
            "reviewer, so she's also useful for research-quality vetting or PhD-intern "
            "recruiting pipelines.",
            "relevance_tags": [
                "Machine Learning expert",
                "Recommendation systems",
                "Research leadership",
                "Ranking / A-B testing",
            ],
            "connection_notes": [],
            "source_type": "text",
            "created_at": NOW,
            "updated_at": NOW,
            "embedding": EMBEDDING_PLACEHOLDER,
        },
    },
    {
        "file": "04_sofia_ibarra.json",
        "data": {
            "id": str(uuid.uuid4()),
            "full_name": "Sofia Ibarra",
            "headline": "VP of Product, Clinical Workflows @ Ardent Health Systems | "
            "Practicing physician turned product leader",
            "linkedin_url": "https://www.linkedin.com/in/sofia-ibarra-example",
            "photo_url": None,
            "current_company": "Ardent Health Systems",
            "current_title": "VP of Product, Clinical Workflows",
            "location": "Nashville, Tennessee Metropolitan Area",
            "industry": "Healthcare / Health Tech",
            "summary": "Physician (MD) turned product leader with an MPH in health "
            "informatics. Leads clinical-workflow product at Ardent Health Systems "
            "across 30 hospitals; previously built a clinical decision support product "
            "team from scratch and shipped an FDA Class II SaMD-cleared tool.",
            "experience": [
                {
                    "title": "VP of Product, Clinical Workflows",
                    "company": "Ardent Health Systems",
                    "start_date": "2023-02",
                    "end_date": None,
                    "description": "Owns product strategy for clinician-facing EHR "
                    "workflow tools across 30 hospitals. Led launch of an AI-assisted "
                    "clinical documentation tool now used by 1,200 physicians.",
                },
                {
                    "title": "Director of Product",
                    "company": "Cadence Health",
                    "start_date": "2020-06",
                    "end_date": "2023-01",
                    "description": "Built and led the clinical decision support "
                    "product team (0 to 9 people). Shipped a Class II SaMD-cleared "
                    "risk-scoring tool.",
                },
                {
                    "title": "Internal Medicine Physician",
                    "company": "Vanderbilt University Medical Center",
                    "start_date": "2014-07",
                    "end_date": "2020-05",
                    "description": None,
                },
            ],
            "education": [
                {
                    "school": "Johns Hopkins Bloomberg School of Public Health",
                    "degree": "MPH",
                    "field_of_study": "Health Informatics",
                    "start_year": "2018",
                    "end_year": "2020",
                },
                {
                    "school": "Vanderbilt University School of Medicine",
                    "degree": "MD",
                    "field_of_study": None,
                    "start_year": "2010",
                    "end_year": "2014",
                },
            ],
            "skills": [
                "Healthcare Product Management",
                "Clinician Stakeholder Management",
                "Product Strategy",
            ],
            "technologies": [],
            "domains": ["Healthcare", "Clinical Workflows", "Regulatory / SaMD"],
            "capabilities": [
                "Can advise on FDA Class II SaMD regulatory strategy for clinical "
                "decision support products",
                "Can translate between clinicians and engineering teams",
                "Can lead HIPAA/SOC2 compliance workstreams for health-tech products",
            ],
            "interests": [
                "Clinical decision support",
                "Health informatics",
                "Advisory work for health-tech startups",
            ],
            "relevance_summary": "Sofia is a rare dual-credentialed contact: a "
            "practicing MD who is also a senior product leader, which makes her "
            "unusually good at bridging clinicians and engineers. She's the person to "
            "reach out to for regulatory strategy on clinical decision support (Class "
            "II SaMD), HIPAA/SOC2 compliance planning, or advisory roles at "
            "clinician-facing health-tech startups.",
            "relevance_tags": [
                "Healthcare domain expertise",
                "Product strategy",
                "Regulatory / SaMD",
                "Clinician-engineer bridge",
                "Advisor for health-tech startups",
            ],
            "connection_notes": [],
            "source_type": "text",
            "created_at": NOW,
            "updated_at": NOW,
            "embedding": EMBEDDING_PLACEHOLDER,
        },
    },
    {
        "file": "05_daniel_okafor.json",
        "data": {
            "id": str(uuid.uuid4()),
            "full_name": "Daniel Okafor",
            "headline": "Head of Developer Relations @ Stellarpay | Ex-Twilio, Ex-Stripe | "
            "Conference speaker",
            "linkedin_url": "https://www.linkedin.com/in/daniel-okafor-example",
            "photo_url": None,
            "current_company": "Stellarpay",
            "current_title": "Head of Developer Relations",
            "location": "Toronto, Ontario, Canada",
            "industry": "Developer Tools / API Platforms",
            "summary": "Developer relations leader with a decade of experience building "
            "DevRel functions and developer-facing content at Stripe, Twilio, and now "
            "Stellarpay, where he built the DevRel org from scratch. Frequent "
            "conference speaker and SDK/API-experience specialist.",
            "experience": [
                {
                    "title": "Head of Developer Relations",
                    "company": "Stellarpay",
                    "start_date": "2022-04",
                    "end_date": None,
                    "description": "Built the DevRel function from 1 to 9 people across "
                    "3 regions. Launched the public API docs rewrite and a new SDK "
                    "generation pipeline (7 languages), cutting time-to-first-API-call "
                    "from 45 min to 6 min.",
                },
                {
                    "title": "Senior Developer Advocate, Platform",
                    "company": "Twilio",
                    "start_date": "2018-02",
                    "end_date": "2022-03",
                    "description": "Led platform DevRel for Twilio's Programmable "
                    "Voice and Video APIs. Regular speaker at SIGNAL, KubeCon, and "
                    "regional dev meetups.",
                },
                {
                    "title": "Developer Advocate",
                    "company": "Stripe",
                    "start_date": "2015-06",
                    "end_date": "2018-01",
                    "description": "Early DevRel hire (#340). Wrote integration guides "
                    "and sample apps for the Payments and Connect APIs.",
                },
            ],
            "education": [
                {
                    "school": "University of Waterloo",
                    "degree": "B.Math",
                    "field_of_study": "Computer Science",
                    "start_year": "2011",
                    "end_year": "2015",
                }
            ],
            "skills": [
                "Developer Relations",
                "Technical Writing",
                "Public Speaking",
                "Community Building",
            ],
            "technologies": ["Node.js"],
            "domains": ["Developer Tools", "API Platforms", "Payments"],
            "capabilities": [
                "Can build a Developer Relations org from zero",
                "Can design SDK-generation pipelines across multiple languages",
                "Can advise on developer-experience / API-onboarding funnels",
            ],
            "interests": ["Developer experience", "Public speaking", "API design"],
            "relevance_summary": "Daniel is the go-to contact for building or scaling a "
            "Developer Relations function: he's done it twice (Stripe, then from "
            "scratch at Stellarpay) after cutting his teeth at Twilio's platform team. "
            "Reach out for advice on DevRel hiring, SDK/API onboarding funnels, or "
            "conference speaking connections.",
            "relevance_tags": [
                "Developer Relations",
                "API design",
                "Developer experience",
                "Conference speaker",
                "Payments developer platforms",
            ],
            "connection_notes": [],
            "source_type": "text",
            "created_at": NOW,
            "updated_at": NOW,
            "embedding": EMBEDDING_PLACEHOLDER,
        },
    },
]

for entry in ENTRIES:
    out_path = OUT_DIR / entry["file"]
    out_path.write_text(json.dumps(entry["data"], indent=2), encoding="utf-8")
    print(f"wrote {out_path}")
